services:
- type: web
  name: typesense
  env: docker
  repo: https://github.com/atmaware/typesense-on-render.git
  plan: starter
  healthCheckPath: /health
  disk:
    name: typesense-data
    mountPath: /typesense-data
    sizeGB: 1  
  envVars:
  - key: TYPESENSE_API_KEY
    generateValue: true
  - key: TYPESENSE_DATA_DIR
    value: /typesense-data
  - key: TYPESENSE_ENABLE_CORS
    value: true
  - key: TYPESENSE_LISTEN_PORT
    value: 8107
